name: Run pycodestyle
run-name: ${{ github.actor }} pycodestyle check
on: [push]
jobs:
  run-pycodestyle:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11 #install the python needed
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: execute py script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_SUBMITTER: ${{ github.event.issue.user.login }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          pycodestyle scripts/*.py 
